editorial: export RTCRtpTransceiver "transceiver kind"
w3c/webrtc-pc pull request #2872
Opened 2023-05-15 12:57 UTC by fippo

needed for https://github.com/w3c/webrtc-extensions/pull/167
I am surprised stats didn't already use this...

2023-05-18 13:57 UTC, jan-ivar requested changes

2023-05-18 13:57 UTC, jan-ivar commented on webrtc.html
> +                          of {{RTCRtpTransceiver/transceiver kind}} <var>kind</var>, set
No problem with exporting this is a concept not an API, so we need to leave the [= =] syntax, or the links are formatted like they're code statements, which we don't want. See e.g. https://github.com/w3c/webrtc-pc/pull/2857 for how to do it.

2023-05-18 14:10 UTC, jan-ivar commented on webrtc.html
> +                          of {{RTCRtpTransceiver/transceiver kind}} <var>kind</var>, set
```suggestion
                          of [=RTCRtpTransceiver/transceiver kind=] <var>kind</var>, set
```

2023-06-01 14:09 UTC, jan-ivar approved these changes

2023-06-01 14:10 UTC, Orphis approved these changes

2023-06-01 14:10 UTC, merged